### ISSUE TITLE
Commands TODO

### ISSUE THREAD

**Issue by Kaolhou** [Kaolhou/discord.ts#1]
- [x] ping
- [x] help
- [ ] jogos (pensando em batalha naval e jogo da velha)
- [ ] cotação de moedas
- [ ] lembretes
- [ ] registro em servidor
- [ ] cargo por reação
